apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false # whenever we build an image, do not try to push it off to Docker hub or anything like that
  # googleCloudBuild:
  #   projectId: ticketing-ms-dev-463118
  artifacts:
    - image: simplijulian/ticketing-ms-auth # build
      # us.gcr.io/{projectId}/{service}
      # - image: us.gcr.io/ticketing-ms-dev-463118/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: . # where to sync this file to inside of our running container
