name: tests

on:
  pull_request

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      auth: ${{ steps.changes.outputs.auth }}
      orders: ${{ steps.changes.outputs.orders }}
      payments: ${{ steps.changes.outputs.payments }}
      tickets: ${{ steps.changes.outputs.tickets }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            auth:
              - 'auth/**'
            orders:
              - 'orders/**'
            payments:
              - 'payments/**'
            tickets:
              - 'tickets/**'

  test:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: auth
            changed: ${{ needs.changes.outputs.auth }}
          - service: orders
            changed: ${{ needs.changes.outputs.orders }}
          - service: payments
            changed: ${{ needs.changes.outputs.payments }}
          - service: tickets
            changed: ${{ needs.changes.outputs.tickets }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests if service changed
        if: matrix.changed == 'true'
        run: cd ${{ matrix.service }} && npm install && npm run test:ci