name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, orders, payments, tickets]
    steps:
      - uses: actions/checkout@v4
      - run: cd ${{ matrix.service }} && npm install && npm run test:ci